### ISSUE TITLE
404 with python-pexpect

### ISSUE THREAD

**Issue by mubix** [trustedsec/ptf#525]
```
root@pentestframework:~/ptf# ./ptf 
[*] You can always type ./ptf --no-network-connection to skip the Internet check..
[*] Checking for an Internet connection...
[*] Trying to update myself first.. Then starting framework.
Already up-to-date.
[!] python-pexpect not installed, gitlab will not work
[!] Run pip install python-pexpect to install pexpect for gitlab support.
[!] [!] DANGER WILL ROBINSON. DANGER WILL ROBINSON. Error has occurred.
[!] [!] It's not possible its due to my coding skillz, it must be you? :-)
[!] [!] Printing that error. Get that error. You get it: ['ascii' codec can't encode characters in position 36-47: ordinal not in range(128)]
root@pentestframework:~/ptf# pip install python-pexpect
Collecting python-pexpect
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 795, in get_page
    resp.raise_for_status()
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/models.py", line 893, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 404 Client Error: Not Found for url: https://pypi.org/simple/python-pexpect/
```

**Comment by HackingDave** [comment]
pip install -r requirements.txt
