### ISSUE TITLE
ASCII codec can't encode characters

### ISSUE THREAD

**Issue by mubix** [trustedsec/ptf#526]
On Debian 9 I'm getting an odd error when trying to start PTF
```
root@pentestframework:~/ptf# ./ptf 
[*] You can always type ./ptf --no-network-connection to skip the Internet check..
[*] Checking for an Internet connection...
[*] Trying to update myself first.. Then starting framework.
Already up-to-date.
[!] [!] DANGER WILL ROBINSON. DANGER WILL ROBINSON. Error has occurred.
[!] [!] It's not possible its due to my coding skillz, it must be you? :-)
[!] [!] Printing that error. Get that error. You get it: ['ascii' codec can't encode characters in position 36-47: ordinal not in range(128)]
```

**Comment by mubix** [comment]
Using build 3d1f5cf212aed3ddd26626a4bf71d4b1eae989ff

**Comment by mubix** [comment]
Checking out the prior version solves this issue: 371a67efc80f22085231b0f26beb3ba7732ac401

**Comment by mubix** [comment]
Also passing `-nb` works as well
```
root@pentestframework:~/ptf# ./ptf -nb
[*] You can always type ./ptf --no-network-connection to skip the Internet check..
[*] Checking for an Internet connection...
[*] Trying to update myself first.. Then starting framework.
Already up-to-date.
[*] Operating system detected as: DEBIAN
[*] Welcome to PTF - where everything just works...Because..Aliens

For a list of available commands type ? or help

ptf> exit
```

**Comment by mubix** [comment]
I'm guessing it has to do with this: https://github.com/trustedsec/ptf/pull/524/files#diff-844262b49b2104d077099baaf18020f2

**Comment by mubix** [comment]
Also getting it with search
```
root@pentestframework:~/ptf# ./ptf -nb
[*] You can always type ./ptf --no-network-connection to skip the Internet check..
[*] Checking for an Internet connection...
[*] Trying to update myself first.. Then starting framework.
Already up-to-date.
[*] Operating system detected as: DEBIAN
[*] Welcome to PTF - where everything just works...Because..Aliens

For a list of available commands type ? or help

ptf> search unicorn
[!] [!] DANGER WILL ROBINSON. DANGER WILL ROBINSON. Error has occurred.
[!] [!] It's not possible its due to my coding skillz, it must be you? :-)
[!] [!] Printing that error. Get that error. You get it: ['ascii' codec can't decode byte 0xc5 in position 169: ordinal not in range(128)]
```

**Comment by mubix** [comment]
Tried with the following:
- `Python 2.7.13 (default, Sep 26 2018, 18:42:22) `
- `Python 3.5.3 (default, Sep 27 2018, 17:25:39) `

**Comment by HackingDave** [comment]
Thanks, we just updated the banner today... will revert it back

**Comment by HackingDave** [comment]
just pushed an update, can you give it a shot

**Comment by mubix** [comment]
Works again. Thanks @HackingDave

**Comment by mubix** [comment]
Oddly enough I still run into this with the `search unicorn` command

**Comment by HackingDave** [comment]
weird, let me investigate, can't replicate on Ubuntu, let me check with Debian 9

**Comment by mubix** [comment]
Added trace output:
```
ptf> search unicorn
[!] [!] DANGER WILL ROBINSON. DANGER WILL ROBINSON. Error has occurred.
[!] [!] It's not possible its due to my coding skillz, it must be you? :-)
[!] [!] Printing that error. Get that error. You get it: ['ascii' codec can't decode byte 0xc5 in position 169: ordinal not in range(128)]
Traceback (most recent call last):
  File "./ptf", line 95, in <module>
    src.framework.mainloop()
  File "/root/ptf/src/framework.py", line 781, in mainloop
    handle_prompt(prompt)
  File "/root/ptf/src/framework.py", line 595, in handle_prompt
    search(prompt)
  File "/root/ptf/src/core.py", line 397, in search
    data = open(path, "r").readlines()
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 169: ordinal not in range(128)
```

**Comment by mubix** [comment]
In https://github.com/trustedsec/ptf/blob/976e48b4df36ff40f6ad3050c3032690d9f08a74/src/core.py#L397 

changing the line to `data = open(path, "r", encoding="utf-8").readlines()` fixed search

**Comment by HackingDave** [comment]
Thank you kind sir for troubleshooting that and cut a new release. Closing this out.
