### ISSUE TITLE
pip install always fails with the same error output

### ISSUE THREAD

**Issue by devatnull** [trustedsec/ptf#531]
Hello, I have recently downloaded and installed all the modules from Penetration Testing Framework after the installation pip started to fail terribly, and I believe it started to fail first during the installation and some pip packages were not installed because of this. The error output is the following; (regardless of the package the error is always the same)

### Error

```

 pip install apsdjkaısdj
Traceback (most recent call last):
  File "/usr/bin/pip", line 11, in <module>
    load_entry_point('pip==20.0.2', 'console_scripts', 'pip')()
  File "/usr/lib/python3.8/site-packages/pip/_internal/cli/main.py", line 73, in main
    command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
  File "/usr/lib/python3.8/site-packages/pip/_internal/commands/__init__.py", line 96, in create_command
    module = importlib.import_module(module_path)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 24, in <module>
    from pip._internal.cli.req_command import RequirementCommand
  File "/usr/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 20, in <module>
    from pip._internal.operations.prepare import RequirementPreparer
  File "/usr/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 16, in <module>
    from pip._internal.distributions import (
  File "/usr/lib/python3.8/site-packages/pip/_internal/distributions/__init__.py", line 2, in <module>
    from pip._internal.distributions.wheel import WheelDistribution
  File "/usr/lib/python3.8/site-packages/pip/_internal/distributions/wheel.py", line 5, in <module>
    from pip._internal.utils.wheel import pkg_resources_distribution_for_wheel
  File "/usr/lib/python3.8/site-packages/pip/_internal/utils/wheel.py", line 12, in <module>
    from pip._vendor.six import PY2, ensure_str
ImportError: cannot import name 'ensure_str' from 'six' (/usr/lib/python3.8/site-packages/six.py)



```

### System Specs

> Manjaro Linux
> DISTRIB_ID=ManjaroLinux
> DISTRIB_RELEASE=20.0.1
> DISTRIB_CODENAME=Lysia
> DISTRIB_DESCRIPTION="Manjaro Linux"
> Manjaro Linux
> NAME="Manjaro Linux"
> ID=manjaro
> ID_LIKE=arch
> PRETTY_NAME="Manjaro Linux"
> ANSI_COLOR="1;32"
> HOME_URL="https://www.manjaro.org/"
> SUPPORT_URL="https://www.manjaro.org/"
> BUG_REPORT_URL="https://bugs.manjaro.org/"
> LOGO=manjarolinux

It would be amazing if someone would give me indications on how to solve this issue.

**Comment by realagentwhite** [comment]
What command are you running? Are you calling ptf install all modules or doing it after you run ./ptf ?

**Comment by devatnull** [comment]
> What command are you running? Are you calling ptf install all modules or doing it after you run ./ptf ?

my pip was working fine without the errors before "ptf install all modules" and while it was installing i noticed errors of pip failing to install some modules and packages, after the installation pip was broken.

I should add that the error for pip and pip3 is the same while pip2 does not output errors.

**Comment by realagentwhite** [comment]
How are you running ptf? Is there some way that we can replicate this issue?

**Comment by HackingDave** [comment]
Closing due to inactivity.
